image: python:3.8

stages:
  - build

build_package:
  stage: build
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install pyinstaller
    - pyinstaller main.spec
  artifacts:
    paths:
      - dist/