name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          ${{ if eq(matrix.platform, 'windows-latest') }}venv\Scripts\activate.bat${{ else }}source venv/bin/activate${{ endif }}
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build package
        run: pyinstaller main.spec

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
