name: Build

on:
  push:
    branches:
      - master

jobs:
  build_unix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install nuitka
        run: python -m pip install nuitka

      - name: Build package
        run: python -m nuitka main.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xls2xlsx-linux
          path: ./main.bin

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          .\venv\Scripts\Activate.ps1
          pip install -r requirements.txt

      - name: Install nuitka
        run: python -m pip install nuitka

      - name: Build package
        run: python -m nuitka main.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xls2xlsx-windows
          path: |
            main.exe
            main.cmd

  build_macos:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install nuitka
        run: python -m pip install nuitka

      - name: Build package
        run: python -m nuitka main.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xls2xlsx-macos
          path: ./main.bin
